language: node_js
node_js:
  - "8"
dist: trusty
services: 
  - redis-server
  - mongodb
env:
  - NODE_ENV=ci
  - PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm run start
  - sleep 5
  - npm run test